server:
  port: 8087
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
spring:
  application:
    name: finance-service
  datasource:
    url: jdbc:mysql://localhost:3306/yun6?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123