server:
  port: 8085
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/xk_data?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123