server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
zuul:
  prefix: /api  #添加统一前缀
  routes:
    demo-service: /demo/**
    user-service: /user/**
    new-service: /new/**
    finance-service: /finance/**
    upload-service:
      path: /upload/**
      service: upload-service
      strip-prefix: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 7000 #熔断超时时长:7000
ribbon:
  connetTimeout: 1000 # ribbon链接超时时长
  readTimeout: 35000 # ribbon读取超时时长
  MaxAutoReties: 0 # 当前服务重启次数
  MaxAutoRetiesNextServer: 0 # 切换服务重启次数

